# Generated by Django 4.0.4 on 2022-04-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='tapşırıq')),
                ('answer', models.TextField(verbose_name='cavab')),
                ('to_lesson', models.ManyToManyField(blank=True, related_name='tasks', to='course.lesson')),
            ],
        ),
    ]
