# Generated by Django 4.0.4 on 2022-04-15 19:27

import apps.student.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('student', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name='istifadəçi niki')),
                ('first_name', models.CharField(max_length=50, verbose_name='ad')),
                ('surname', models.CharField(max_length=50, verbose_name='soy ad')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, default='profile_pics/default_avatar.jpg', null=True, upload_to=apps.student.models.photo_upload)),
                ('about', models.TextField(blank=True, max_length=1024, null=True, verbose_name='haqqınızda')),
                ('gender', models.CharField(blank=True, choices=[('m', 'kişi'), ('f', 'qadın')], max_length=1, null=True, verbose_name='gender')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
